### ISSUE TITLE
Clean Docker Hub of Image Name Collisions

### ISSUE THREAD

**Issue by tsconn23** [edgexfoundry/ci-management#195]
With regard to the go services, our current naming convention for Docker images is "docker-<service name>-go". There are old entries in Docker Hub from previous releases that do not follow this convention. When in a hurry during troubleshooting scenarios, this can cause confusion. We should clean out the old entries.

Example:
OLD -- https://hub.docker.com/r/edgexfoundry/core-command-go/
CURRENT -- https://hub.docker.com/r/edgexfoundry/docker-core-command-go/

**Comment by jamesrgregg** [comment]
@tsconn23 for the backlog grooming session tomorrow, let's please discuss this work.

**Comment by tsconn23** [comment]
List of images that I would recommend removing from DockerHub

- edgexfoundry/core-command-go
- edgexfoundry/core-data-go
- edgexfoundry/core-metadata-go
- edgexfoundry/export-client-go
- edgexfoundry/export-distro-go

**Comment by jamesrgregg** [comment]
[#68944] is the EdgeX helpdesk ticket.  Assigning to @MightyNerdEric

**Comment by eb-oss** [comment]
The requested repos have been removed.
