### ISSUE TITLE
Update Java service POMs

### ISSUE THREAD

**Issue by jpwhitemn** [edgexfoundry/ci-management#221]
Update and synchronize the Maven POM files to have the appropriate versions and dependency references in the Java repos (both the service and dependent libraries) listed below.  Java services and libraries on the California branch should have 0.6.0 versions.  Java services and libraries on the Master branch should have the 0.7.0 version.
 
libraries
core-test
core-exception
core-domain
support-domain
device-domain
device-controller
device-scheduling
export-client
core-command-client
export-test
support-notifications-client
export-domain
support-logging-client
core-data-client
core-metadata-client
 
services
support-rulesengine
device-mqtt
device-bacnet
device-bluetooth
device-modbus
device-fishertechnik
device-snmp
device-sdk
device-virtual

**Comment by jamesrgregg** [comment]
@jpwhitemn now that we have archived a lot of the java repos and related jobs, is this Issue still relevant?
It was opened in Oct 2018

**Comment by jpwhitemn** [comment]
No - I think we can close this issue.  Rules engine is the last and we have that one covered.  We had this issue in place because we feared we may have to go back and fix a bug or issue but that never happened.

    On Thursday, February 14, 2019, 6:43:53 PM CST, jamesrgregg <notifications@github.com> wrote:  
 
 
@jpwhitemn now that we have archived a lot of the java repos and related jobs, is this Issue still relevant?
It was opened in Oct 2018

**Comment by jamesrgregg** [comment]
closing issue per @jpwhitemn direction
