### ISSUE TITLE
Add LICENSE file to this repo

### ISSUE THREAD

**Issue by jpwhitemn** [edgexfoundry/ci-management#263]
Please add a LICENSE file to the root of this repo per https://wiki.edgexfoundry.org/pages/viewpage.action?pageId=21823866

**Comment by jamesrgregg** [comment]
@jpwhitemn I'm not able to assign this issue to myself.  Can I get permissions please?  I attempted to work this last night but had to backout my PR.

**Comment by jpwhitemn** [comment]
Thanks @jamesrgregg.  I don't have rights either.  I think Jeremy was the only one with commit rights to this repo (along with another from LF).  Will send out notice to helpdesk to get you permissions.
May not be reacted to until new year.

**Comment by jamesrgregg** [comment]
@JPWKU now that PR #265 was merged, how does this Issue get closed?

**Comment by jpwhitemn** [comment]
James,In the future, when submitting a PR, if you put "Fixes #263" in the comments of the PR, it will automatically close out the issue for you when it is merged.  Otherwise, you just do it manually by going to the issue and push the Close issue button - and put a comment in that says what PR resolved the issue.
jim

    On Thursday, January 3, 2019, 2:53:29 PM CST, jamesrgregg <notifications@github.com> wrote:  
 
 
@JPWKU now that PR #265 was merged, how does this Issue get closed?

**Comment by jamesrgregg** [comment]
Issue resolved per PR #265
