### ISSUE TITLE
Land new infrastructure for TIG stack

### ISSUE THREAD

**Issue by jamesrgregg** [edgexfoundry/ci-management#298]
Land new infrastructure for TIG stack
- backup plan if the ELK stack proposed by LF Infrastructure team doesn't work.

US3324

**Comment by jamesrgregg** [comment]
Based on conversation with @MightyNerdEric the plan is now to go with a dedicated TIG stack for EdgeX.  

- shared CloudFormation and telemetry stack on 2/20/19.
Pending review with the LF Infrastructure team.

**Comment by eb-oss** [comment]
LF work on this issue is being tracked on the following tickets:
https://jira.linuxfoundation.org/browse/INFRA-4291
https://jira.linuxfoundation.org/browse/RELENG-1821

**Comment by jamesrgregg** [comment]
Working with LF Infrastructure team to finalize this landing - backups, monitoring and dashboards WIP

**Comment by jamesrgregg** [comment]
TIG stack landed and connectivity tested from sandbox
