### ISSUE TITLE
Sigul (GPG signed artifacts) - needs to be done with an automated (faceless service account does the actual signing on the artifact)

### ISSUE THREAD

**Issue by jamesrgregg** [edgexfoundry/ci-management#304]
- spike to figure out sigul - using a faceless service account (Jenkins user)
 - configure Jenkins to use Sigpul
 - test / verification of signed tagging process

US3476

**Comment by jamesrgregg** [comment]
Additional scope of work to be completed by LF to enhance sigul
This work will be tracked on the following ticket: https://jira.linuxfoundation.org/browse/RELENG-1851

**Comment by jamesrgregg** [comment]
@MightyNerdEric please confirm that this can be closed.  I think you configured settings for LFTOOLS / Sigul signing already.

**Comment by eb-oss** [comment]
Yes, this is all done. The improved documentation you requested on the RT ticket has also been added to lftools, and will be part of the next release.
