### ISSUE TITLE
New JJB needed for device-virtual service

### ISSUE THREAD

**Issue by jamesrgregg** [edgexfoundry/ci-management#323]

**Comment by FelixTing** [comment]
Hi @jamesrgregg 
The device-virtual-service initial code is ready. And I also prepared the files needed for JJB: https://git.io/fjk7T
If you agree, I can create a PR for this.
But I don't have the right to add the mvn-settings file (device-virtual-go-settings) on the EdgeXFoundry Jenkins maser, which needs help from your side.

I am new to JJB. Please advice as necessary if I am doing something wrong.
Thank you.

**Comment by jamesrgregg** [comment]
@FelixTing looks like we need to get your code into edgexfoundry-holding repo first so we can then coordinate getting additional eyes on it from the tsc and community.  Once approved, we can coordinate the move to the main edgesfoundry along with the reqired settings.  We'll have to deploy to sandbox first as well.

**Comment by jamesrgregg** [comment]
@FelixTing ..sorry for the confusion.. this doesn't need to go to holding repo first.  
I see this is a fork of ci-management.  Open the PR and we can work to get the settings files set up for this job.  It does need to go to sandbox first.  Do you want to try to deploy this yourself to sandbox?  If so, I can coordinate your access.

**Comment by FelixTing** [comment]
@jamesrgregg Thanks for the reply.
The PR is open: #337 
Sure, I want to try it. Learning CI skills is interesting for me.😄

**Comment by jamesrgregg** [comment]
jjb has been created
