### ISSUE TITLE
remove California from snap jjb template

### ISSUE THREAD

**Issue by jamesrgregg** [edgexfoundry/ci-management#328]
The California snap builds are failing and considered obsolete.
Need to remove the following from the jjb template
https://github.com/edgexfoundry/ci-management/blob/master/jjb/edgex-go/edgex-go-snap.yaml#L11-L13

**Comment by jamesrgregg** [comment]
@tmpowers - this was requested today by @anonymouse64 in the DevOps WG.

**Comment by anonymouse64** [comment]
so one thing I was wondering about is if it's possible to keep the `verify` jobs running in case we do need to ever do a backport, and just remove the `stage` jobs, which are completely broken and failing.

It is okay however if we can't selectively remove the stage jobs and need to just remove all of the california snap jobs, the likelihood of needing to port any more code back to california is basically 0% at this point.

**Comment by jamesrgregg** [comment]
I think if there was a chance of that, we just add the stream back into the jjb template.

~ James Gregg

**Comment by anonymouse64** [comment]
Sure that's fine then

**Comment by eb-oss** [comment]
If you take a look at the file that creates these jobs, you can see why you can't really remove all but the verify job:
https://github.com/edgexfoundry/ci-management/blob/master/jjb/edgex-go/edgex-go-snap.yaml

The jobs are set at the project level, and then branches are set up as "streams." So in this case, I think what we'll want to do is remove the california stream, which will remove all associated jobs.

**Comment by anonymouse64** [comment]
That's why I asked to see if there was another way to do this, but if
there's not then removing the whole California stream is fine

**Comment by tmpowers** [comment]
Created PR, https://github.com/edgexfoundry/ci-management/pull/331, to address this.

**Comment by jamesrgregg** [comment]
Resolved
