### ISSUE TITLE
Fix edgex-ui-go to use new go modules build job 

### ISSUE THREAD

**Issue by anonymouse64** [edgexfoundry/ci-management#356]
The `edgex-ui-go` master branch recently switched to using go modules, and now has jenkins jobs failing. See for example: https://jenkins.edgexfoundry.org/job/edgex-ui-go-master-verify-go/46/console from https://github.com/edgexfoundry/edgex-ui-go/pull/85

I think the reason for this is that the default version of go is too old and doesn't support modules by default, and so we need to use the updated version of go that we use for i.e. edgex-go. AFAICT, for the edgex-go jobs this is accomplished in the job definition yaml with this snippet:

https://github.com/edgexfoundry/ci-management/blob/457179db392ba1190239e3e64b5d4892f6fb8769/jjb/edgex-go/edgex-go.yaml#L8-L13

Does that mean all we need to do to get this to work on edgex-ui-go is to add that `go-root` spec to the master stream?

**Comment by eb-oss** [comment]
Yes, I think you'll need the `install_custom_golang.sh` script and the `go-root` definition. But it looks like edgex-ui-go.yaml has a global `pre_build_script` already defined, so you'll need to make sure that overwriting that won't break anything.

**Comment by anonymouse64** [comment]
After adding those to the master stream for edgex-ui-go, unfortunately the build still fails, however it seems the issue could be with some missing dependencies not checked into the go.mod file. I am investigating with https://github.com/edgexfoundry/edgex-ui-go/pull/87
