### ISSUE TITLE
Snap builds should use unbuffer for better output logging

### ISSUE THREAD

**Issue by anonymouse64** [edgexfoundry/ci-management#369]
See https://forum.snapcraft.io/t/fixing-out-of-order-message-output-when-piping-snapcrafts-output-to-file/9176 for full explanation, but basically we should update the docker build script for the snap to use unbuffer so that the log looks a bit better as oftentimes on jenkins logs the error gets output to stderr much earlier than the corresponding output at the same time on stdout, hence one has to do some backtracking when debugging the logs.

Originally filed as https://github.com/edgexfoundry/edgex-go/issues/1018 but now since the snap build scripts are here, migrating to this repo

**Comment by jamesrgregg** [comment]
@tonyespy could you please take a look at this issue and let us know if we need to consider this for Hanoi scope?  Thank you.

**Comment by tonyespy** [comment]
@jamesrgregg yes, we should consider it for Hanoi as it's a trivial change (a one-liner) to the snap build script which will make the resulting build logs easier to grok.

**Comment by anonymouse64** [comment]
Unclear if this can be closed as done yet, I see that https://github.com/edgexfoundry/ci-build-images/pull/140 was merged, but I don't know how to see any snap builds that would have been done after that was merged. @ernestojeda can you provide me with a link to a jenkins pipeline job that ran with that PR to check the build log?

**Comment by ernestojeda** [comment]
@anonymouse64 Here is the link the snap build image used in the pipeline:

https://jenkins.edgexfoundry.org/view/EdgeX%20Foundry%20Project/job/edgexfoundry/job/ci-build-images/job/snapcraft-builder/

It has been built 3 times since the July 14 merge. I manually ran the builds each time. We have a story in our backlog to get the weekly builds setup with a cron trigger.

**Comment by anonymouse64** [comment]
@ernestojeda can you provide a link to a job that actually used that image? That link you provided just seems to be for building the image but I would like to see a snap being built with that image to confirm the bug is actually fixed

**Comment by ernestojeda** [comment]
> @ernestojeda can you provide a link to a job that actually used that image? That link you provided just seems to be for building the image but I would like to see a snap being built with that image to confirm the bug is actually fixed

edge-go-daily-snap runs every day. You can see the latest here:
https://jenkins.edgexfoundry.org/blue/organizations/jenkins/edgexfoundry%2Fcd-management/detail/edgex-go-daily-snap/141/

You can see the history on this page:
https://jenkins.edgexfoundry.org/job/edgexfoundry/job/cd-management/job/edgex-go-daily-snap/

And these are the docker images being used if you want to pull them directly:

```
docker pull nexus3.edgexfoundry.org:10003/edgex-devops/edgex-snap-builder@sha256:af8a54c7bc77af20a24fc779da6a179edb230b027a9915447f6ddb0093e77608
docker pull nexus3.edgexfoundry.org:10003/edgex-devops/edgex-snap-builder-arm64@sha256:6e406ae1453d9e8d8e9e409efff2bb31ab6f017c918e683fbe291fd96f16a4ed
```

**Comment by anonymouse64** [comment]
Thanks for that this looks good to me now
