### ISSUE TITLE
Add schedule on performance test job

### ISSUE THREAD

**Issue by cherrycl** [edgexfoundry/ci-management#375]
Before the schedule sets on the performance test job, the job has to trigger manually.
Planning set the schedule to "H 4 * * 6". ( The job will run at every Saturday 4 AM UTC time)

**Comment by jamesrgregg** [comment]
@cherrycl I think this job was triggered and then it seemingly hung.  Can you verify that the job now has the schedule?

**Comment by cherrycl** [comment]
@jamesrgregg The job was triggered and aborted by manual. I didn't add the schedule for the job yet. I am currently working on adding the schedule.
