### ISSUE TITLE
New Jenkins Pipeline Needed for : edgex-ui-clojure 

### ISSUE THREAD

**Issue by jamesrgregg** [edgexfoundry/ci-management#388]
Assigned to: @tmpowers 

edinburgh branch / code freeze

https://github.com/edgexfoundry/edgex-ui-clojure

NEW CODE DROP HAS NO BUILD AUTOMATION

US4514

**Comment by dweomer** [comment]
edgexfoundry/edgex-ui-clojure#18 fixed build on arm64

**Comment by jamesrgregg** [comment]
pipeline is created and settings file created today - working on build issues related to settings file
 JSD #IT-16543
