### ISSUE TITLE
Update snapcraft inside docker to use new setup from snapcraft

### ISSUE THREAD

**Issue by anonymouse64** [edgexfoundry/ci-management#449]
The current implementation of installing snapcraft inside a docker container works, but is out-dated from the new method that is used upstream as of https://github.com/snapcore/snapcraft/pull/2588 and https://github.com/snapcore/snapcraft/pull/2591. It may also be possible to use the upstream docker containers, or at least minimally change our Dockerfile to build on top of theirs

**Comment by abitrolly** [comment]
Why you need `snapcraft` inside docker in this specific project?

**Comment by anonymouse64** [comment]
@abitrolly We don't use build.snapcraft.io or launchpad to build EdgeX snaps, so it's easier for the jenkins infrastructure to build the snap since docker is already used to build other artifacts for the project.

**Comment by abitrolly** [comment]
And what problems do you experience with official Docker images? Is that inability to target `core18` with dockerized `snapcraft`?

**Comment by anonymouse64** [comment]
Well when we initially started it there were multiple issues, some of which have been resolved, but the main reasons right now are:
* no non-amd64 arch images available (we need arm64)
* need to build on core18 base

**Comment by abitrolly** [comment]
I've got automatic job that builds Ubuntu 18.04 container for core18 - https://hub.docker.com/r/yakshaveinc/snapcraft on commit. I never did docker builds for arm64. Does it require arm64 system?

**Comment by anonymouse64** [comment]
Yes you more than likely need an arm64 system, however you can create arm64 VM's, which is what we do in Jenkins. You may be able to cross-compile depending on how simple your snap is, but it's quite involved for a snap as complex as edgexfoundry.

**Comment by jamesrgregg** [comment]
@tonyespy could you please take a look at this issue and let us know if we need to consider this for Hanoi scope?  Thank you.

**Comment by tonyespy** [comment]
@jamesrgregg yes, we should consider this for hanoi. This is something I can definitely help with.
