### ISSUE TITLE
Performance-test-master does not time out properly

### ISSUE THREAD

**Issue by eb-oss** [edgexfoundry/ci-management#450]
@cherrycl Per this line, it appears that you intended the job to timeout after 60 minutes:
https://github.com/edgexfoundry/ci-management/blob/8e5e774255c5d754e047df5e0ce011f724ab597b/jjb/performance-test/performance-test.yaml#L17

However, because this is a pipeline job, this setting is not part of the config. I believe you'll need to add a timeout in the Jenkinsfile.

**Comment by cherrycl** [comment]
Since the timeout setting does not work for pipeline job, I will remove it.
