### ISSUE TITLE
Multiple Release Tags for the Same Commit

### ISSUE THREAD

**Issue by tsconn23** [edgexfoundry/ci-management#452]
Take a look at the release history at this link.

https://github.com/edgexfoundry/go-mod-messaging/releases

You will see that multiple tagged versions have the same commit SHA. I would think that shouldn't be happening.

I haven't reviewed the release history for go-mod-registry or go-mod-core-contracts but might want to take a look there as well.

**Comment by dweomer** [comment]
I am pretty sure this is due to commits from edgexfoundry/edgex-global-pipelines triggering builds (which is a known bug until we migrate to the github org branch plugin for jenkins pipelines). I am building up a timeline with cross references to validate this assertion.

**Comment by dweomer** [comment]
> I am pretty sure this is due to commits from edgexfoundry/edgex-global-pipelines triggering builds (which is a known bug until we migrate to the github org branch plugin for jenkins pipelines). I am building up a timeline with cross references to validate this assertion.

The thing that worries me is that `git-semver` should be blocking such (unless say there is a race condition but these tag dupes are hours and sometimes days apart).

**Comment by dweomer** [comment]
Poking around:
```bash
$ git remote -v
global	git@github.com:edgexfoundry/edgex-global-pipelines.git (fetch)
global	git@github.com:edgexfoundry/edgex-global-pipelines.git (push)
origin	git@github.com:dweomer/edgexfoundry-go-mod-messaging.git (fetch)
origin	git@github.com:dweomer/edgexfoundry-go-mod-messaging.git (push)
upstream	git@github.com:edgexfoundry/go-mod-messaging.git (fetch)
upstream	git@github.com:edgexfoundry/go-mod-messaging.git (push)

$ TZ=UTC git for-each-ref --sort=taggerdate --format '%(refname) %(objectname) %(taggerdate:iso-local)' refs/tags | sort -r
refs/tags/v0.1.9 d8d81f36f201558a79dfef7e32239e0f1ee66c00 2019-07-16 21:52:07 +0000
refs/tags/v0.1.8 b9e4638496113b5d496a24b4aa2be228672a37cf 2019-07-16 18:41:50 +0000
refs/tags/v0.1.7 de45912ed789568c0bec14d546473eb5b81f9626 2019-07-16 17:24:12 +0000
refs/tags/v0.1.6 20d2997d909f88609ff4744c9f6870ba0e92bb39 2019-07-10 14:35:15 +0000
refs/tags/v0.1.5 7d24d2b54a86e0c49c22c46bcd3c50436e6b5ccb 2019-07-08 16:22:25 +0000
refs/tags/v0.1.4 c3c0a69c87ab5826c9260b0c98994ac139cdef26 2019-07-01 20:49:23 +0000
refs/tags/v0.1.3 546e339aac540b72df76fdd8beff4a5ee1b9a600 2019-06-27 23:26:27 +0000
refs/tags/v0.1.2 bea70a784424568f58050ce615166eaa251f4a3e 2019-06-20 19:53:13 +0000
refs/tags/v0.1.1 06493e99d8ff5e1aac6af447d1fc142728b85eee 2019-06-14 21:51:36 +0000
refs/tags/v0.1.0 d419c33f88a01a7dcdd3ecbe44478ab91645d1a7 2019-05-28 21:13:50 +0000
refs/tags/v0.0.0 41d42da116c2b1c35b63b19cf8636142ff053b46 2019-05-17 14:13:07 +0000

$ TZ=UTC git log --date=iso-local -11 --pretty='format:%H %cd %D' upstream/master
53a6bbf43407ca7522e57b582e3b905493992809 2019-07-16 18:33:00 +0000 HEAD -> master, tag: v0.1.9, tag: v0.1.8, upstream/master, origin/master, origin/HEAD
37dddbb11ab4d22a9bbbd89b724866e9f40efe54 2019-07-15 23:36:33 +0000 
a890a02ef42a965dafd5397ea306f43b216bb015 2019-07-10 14:26:28 +0000 tag: v0.1.7, tag: v0.1.6
8a7864e25347004b93e696f26b74d0c6a56b78e3 2019-07-08 16:12:31 +0000 tag: v0.1.5
3f7bb616628311ee69496e5c10b91ec2e3888e2a 2019-05-28 21:04:44 +0000 tag: v0.1.4, tag: v0.1.3, tag: v0.1.2, tag: v0.1.1, tag: v0.1.0
407d7a2e54f09bc87af3608fbcc7b78d661db40f 2019-05-16 18:29:30 +0000 tag: v0.0.0
18e14ad62fb232c3fddceea415da29d0b56d5906 2019-05-16 17:44:59 +0000 
04f9582c7a084d9f09edd456a75a101bff6e66ef 2019-05-07 19:27:40 +0000 
179a3fcd35b6b8bf2bf0be29a1cd7beb59c482e8 2019-05-07 17:12:40 +0000 
cedb33322066e3e5c564a6b9b15e37a20ed30572 2019-05-07 16:16:52 +0000 
bd1d7220b8052ab1f959e44beed737feafbbf3c5 2019-05-07 16:03:34 +0000

$ TZ=UTC git log --date=iso-local -11 --pretty='format:%H %cd %D' global/master
e1ccf7a19ad62de962111155ad7ad3e0760f6dc4 2019-07-16 21:42:53 +0000 global/master
76013f7f54eae1425e0266af8cb8d549422befe1 2019-07-16 20:40:32 +0000 
ff600a04c7f514aa48371867595d5aac37143839 2019-07-16 17:06:47 +0000 
e74a023a3ed10bc07ebae2daeb7179facf5bab17 2019-07-16 16:09:26 +0000 
8c8a76faeb8b7bf487af3f098d7a5ae78396248e 2019-07-01 20:37:44 +0000 
379c93d48cf650a38e6d4c0d1ca6ade312b71f29 2019-06-28 22:00:51 +0000 
0e262ee56b6ae0356c561cfa58d26d7b6a03f9f2 2019-06-28 21:49:18 +0000 
643a73119fac2f1c6d4cc4e2a286ff6ae5a6c1bd 2019-06-27 23:18:29 +0000 
12e107b3329d7af36d3d38a8a4998734f9d3ea04 2019-06-27 22:22:21 +0000 
11274cc4b52f191235b21fa3d49b3c7325b0728e 2019-06-20 19:33:39 +0000 
0980eece152547674e3cc4f7c88bcb37d529c1ec 2019-06-20 18:33:48 +0000
```

https://jenkins.edgexfoundry.org/job/go-mod-messaging-merge-pipeline/changes:
![Screen Shot 2019-07-17 at 12 49 47 PM](https://user-images.githubusercontent.com/1033444/61406840-87962880-a891-11e9-94ac-a15084d6b37b.png)

**Comment by dweomer** [comment]
Please notice that build times for `go-mod-messaging` are about 10-15 minutes total and that tag timestamps lag commit timestamps by roughly the same amount of time.

Based on the information gathered above we have these correlations (bolded lines are the triggering events):

- [v0.1.9](https://github.com/edgexfoundry/go-mod-messaging/releases/tag/v0.1.9)
  - https://github.com/edgexfoundry/edgex-global-pipelines/commit/e1ccf7a19ad62de962111155ad7ad3e0760f6dc4 (trigger)
    - https://github.com/edgexfoundry/edgex-global-pipelines/commit/76013f7f54eae1425e0266af8cb8d549422befe1
  - https://github.com/edgexfoundry/go-mod-messaging/commit/53a6bbf43407ca7522e57b582e3b905493992809

- [v0.1.8](https://github.com/edgexfoundry/go-mod-messaging/releases/tag/v0.1.8)
  - https://github.com/edgexfoundry/go-mod-messaging/commit/53a6bbf43407ca7522e57b582e3b905493992809 (trigger)

- [v0.1.7](https://github.com/edgexfoundry/go-mod-messaging/releases/tag/v0.1.7)
  - https://github.com/edgexfoundry/edgex-global-pipelines/commit/ff600a04c7f514aa48371867595d5aac37143839 (trigger)
    - https://github.com/edgexfoundry/edgex-global-pipelines/commit/e74a023a3ed10bc07ebae2daeb7179facf5bab17
  - https://github.com/edgexfoundry/go-mod-messaging/commit/a890a02ef42a965dafd5397ea306f43b216bb015

- [v0.1.6](https://github.com/edgexfoundry/go-mod-messaging/releases/tag/v0.1.6)
  - https://github.com/edgexfoundry/go-mod-messaging/commit/a890a02ef42a965dafd5397ea306f43b216bb015 (trigger)

- [v0.1.5](https://github.com/edgexfoundry/go-mod-messaging/releases/tag/v0.1.5)
  - https://github.com/edgexfoundry/go-mod-messaging/commit/8a7864e25347004b93e696f26b74d0c6a56b78e3 (trigger)

- and so on ...

I need to dig into why commits to `edgexfoundry/edgex-global-pipelines` seem to be sidestepping the `git-semver` check.

**Comment by dweomer** [comment]
Ah, it's because of this old code that was deemed necessary, albeit temporarily, to work with sigul tag signing: https://github.com/edgexfoundry/go-mod-messaging/blob/53a6bbf43407ca7522e57b582e3b905493992809/Jenkinsfile#L83

**Comment by dweomer** [comment]
Love to stumble over land-mines that we placed ourselves (from https://github.com/search?q=git+tag+-a+edgexfoundry&type=Code):

- https://github.com/edgexfoundry/go-mod-registry/blob/a61e77f41a1987c1352aa75eecb2f48bd4af0310/Jenkinsfile#L83
- https://github.com/edgexfoundry/go-mod-messaging/blob/a890a02ef42a965dafd5397ea306f43b216bb015/Jenkinsfile#L83
- https://github.com/edgexfoundry/go-mod-core-contracts/blob/125f6133d42fbbaf6337fa9308860fb8e2005361/Jenkinsfile#L83
- https://github.com/edgexfoundry/app-functions-sdk-go/blob/12879fde92789a449b44d5e18165f7ab91dfea10/Jenkinsfile#L85

I'll get some pull requests lined up within an hour or two.

**Comment by dweomer** [comment]
@tsconn23 as discussed I have asked @lenny-intel to approve and merge the 4 linked PRs
- https://github.com/edgexfoundry/go-mod-registry/pull/21
- https://github.com/edgexfoundry/go-mod-messaging/pull/30
- https://github.com/edgexfoundry/go-mod-core-contracts/pull/117
- https://github.com/edgexfoundry/app-functions-sdk-go/pull/139

But before we close this out we should consider investigating whether the multiple tags will cause problems when building or updating downstream projects with `go mod` referencing duped tags. If there are issues we should consider submitting ticket(s) to LF to delete the duped tags.

**Comment by dweomer** [comment]
Having thought about this on the drive in to work, going to close this out and wait for any reports of `go mod` / `go build` tooling invocations failing because of duped tags.
