### ISSUE TITLE
New Jenkins Pipeline needed for app-service-configurable

### ISSUE THREAD

**Issue by lenny-goodell** [edgexfoundry/ci-management#464]
New Jenkins Pipeline needed for app-service-configurable
We'll need a pipeline job for the following repo.

https://github.com/edgexfoundry/app-service-configurable

It looks like all that's currently assigned is the DCO check. We'll want to treat this the same way we do device services, i.e. device-virtual-go, etc.

**Comment by jamesrgregg** [comment]
this is work slated for the next Sprint 41.

**Comment by lenny-goodell** [comment]
K, I made an attempt at the new JJB file and submitted the PR #465
