### ISSUE TITLE
go-mod-secrets-verify-pipeline Should be Required

### ISSUE THREAD

**Issue by tsconn23** [edgexfoundry/ci-management#478]
Currently the go-mod-secrets-verify-pipeline job is not required so I can merge an PR even if the pipeline is failing.

<img width="717" alt="Screen Shot 2019-09-09 at 2 38 34 PM" src="https://user-images.githubusercontent.com/1342980/64561178-b7046700-d30f-11e9-8393-eab613200588.png">

At the moment it's failing on PR https://github.com/edgexfoundry/go-mod-secrets/pull/20 but I could still merge it if I wanted to.

**Comment by eb-oss** [comment]
This is something that needs to be changed administratively in Github. Please file issues like this at support.linuxfoundation.org. https://docs.releng.linuxfoundation.org/en/latest/helpdesk.html

I'm working the queue this week, so I'll grab this and get it done as soon as I see it come in. Sorry to make you file a ticket when I've obviously seen this here, but we're really trying to get a record of all the work we do in one place.

**Comment by tsconn23** [comment]
Ticket #IT-17481
