### ISSUE TITLE
Add JJB for edgex-taf-common docker image build job

### ISSUE THREAD

**Issue by weichou1229** [edgexfoundry/ci-management#515]
This issue created for https://github.com/edgexfoundry/edgex-taf-common/issues/6
The purpose is to create a jenkins job for docker image build job.

**Comment by weichou1229** [comment]
@ernestojeda 
After PR merged, Jenkins trigger the job but got an error:
```
17:23:49 ERROR: not able to provide the file [ManagedFile: id=edgex-taf-common-settings, targetLocation=, variable=SETTINGS_FILE], can't be resolved by any provider - maybe it got deleted by an administrator?
```
Do you know how to resolve it? 
https://jenkins.edgexfoundry.org/job/edgex-taf-common-pipeline-webhooks/1/console

**Comment by jamesrgregg** [comment]
We need the LF to set the settings. It requires a Jira ticket.

**Comment by jamesrgregg** [comment]
IT-18472

**Comment by weichou1229** [comment]
@jamesrgregg 
Thanks!  The Jenkins job passed but I didn’t find the image on the [nexus repo](https://nexus3.edgexfoundry.org/).
I defined the Jenkinsfile here https://github.com/edgexfoundry/edgex-taf-common/blob/master/Jenkinsfile
Do you know how to check the job works correctly?

**Comment by weichou1229** [comment]
Should I update the Jenkinsfile just like [this PR](https://github.com/edgexfoundry/device-bacnet-c/pull/31)?

**Comment by eb-oss** [comment]
If you look at the logs, nothing useful is happening. https://jenkins.edgexfoundry.org/job/edgex-taf-common-pipeline-webhooks/3/console

I'm not sure if you want the same changes as device-bacnet-c, but there's definitely something wrong with this job as it is.

**Comment by weichou1229** [comment]
@MightyNerdEric 
Sorry, I have no idea why Jenkins didn't run the job.
I can login the Jenkins but I didn't see **Build buttom** which can trigger the job.
Do you know how to trigger the jenkins job?  Is there some way I can verify the job?

**Comment by eb-oss** [comment]
You can't retrigger manually. For testing, please use the sandbox.

**Comment by weichou1229** [comment]
@askb 
Could you please help check the Jenkins build job error?

I noticed you update the settings, but it did not work in the sandbox.

https://jenkins.edgexfoundry.org/sandbox/view/All/job/edgex-taf-common-verify-pipeline/1/console

```
ERROR: not able to provide the file [ManagedFile: id=taf-settings, targetLocation=null, variable=SETTINGS_FILE], can't be resolved by any provider - maybe it got deleted by an administrator?
Finished: FAILURE
```

https://jenkins.edgexfoundry.org/sandbox/view/All/job/edgex-taf-common-pipeline-webhooks/1/console
```
16:06:11 ERROR: not able to provide the file [ManagedFile: id=taf-settings, targetLocation=, variable=SETTINGS_FILE], can't be resolved by any provider - maybe it got deleted by an administrator?
```

**Comment by lranjbar** [comment]
Since we have the new Geneva pipelines we have a failing job. After a quick look I believe we can migrate this one to use edgeXBuildDocker. That should get this working quickly.

See build failures: https://jenkins.edgexfoundry.org/view/EdgeX%20Foundry%20Project/job/edgexfoundry/job/edgex-taf-common/

@ernestojeda @jamesrgregg @soda480 @weichou1229 @cloudxxx8

**Comment by soda480** [comment]
@weichou1229 @cloudxxx8 
Does your team plan to release the taf-common docker image? The reason I ask is so that we can configure the job to deploy the docker image to the appropriate Nexus repository.

**Comment by soda480** [comment]
@weichou1229 @cloudxxx8 
I noticed the previous build was attempting to tag the docker image with 1.1.1? Is there a reason you needed it tagged with that?

**Comment by weichou1229** [comment]
@soda480 

> Does your team plan to release the taf-common docker image? 

No, it only for internal usage like newman.

> I noticed the previous build was attempting to tag the docker image with 1.1.1? Is there a reason you needed it tagged with that?

Do you know what is the appropriate tag for the testing tool?  Could you help to change the tag?

**Comment by soda480** [comment]
@weichou1229 
> Do you know what is the appropriate tag for the testing tool? Could you help to change the tag?

We will be using git semver to do the tagging, since this will be the first release of this image git semver will tag it with v0.0.0. But we have the ability to tag it manually to a specific version (if need be).  

@lranjbar , do you have any recommendations on what version we should tag this image with?

**Comment by lranjbar** [comment]
Since this is an internal image, I see no harm starting with `v0.0.1` and just increment it as we see fit. For testing it will be better to use the `master` tag because that will be a sliding tag.

**Comment by soda480** [comment]
@weichou1229 
The Jenkins job is working and published the `docker-edgex-taf-common` Docker image to Nexus snapshots with tag of `v0.0.1`

**Comment by weichou1229** [comment]
@soda480 
Thanks a lot for your help.

I can saw it show on the https://nexus3.edgexfoundry.org/  but I can't pull it on my laptop with following commands:

* `docker pull nexus3.edgexfoundry.org:10004/docker-edgex-taf-common:v0.0.1`
```
Error response from daemon: manifest for nexus3.edgexfoundry.org:10004/docker-edgex-taf-common:v0.0.1 not found: manifest unknown: manifest unknown
```

*  `docker pull nexus3.edgexfoundry.org:10004/docker-edgex-taf-common:0.0.1 `
 ```
 Error response from daemon: manifest for nexus3.edgexfoundry.org:10004/docker-edgex-taf- common:0.0.1 not found: manifest unknown: manifest unknown
 ```

Did I miss something?

**Comment by weichou1229** [comment]
Sorry, no problem now. I change the port to 10003 and it works.
`docker pull nexus3.edgexfoundry.org:10003/docker-edgex-taf-common:0.0.1`
