### ISSUE TITLE
Root cause analysis of the ARM failures for blackbox-testing - Infrastructure failures

### ISSUE THREAD

**Issue by lranjbar** [edgexfoundry/ci-management#520]

**Comment by jamesrgregg** [comment]
Discussion in ww04 DevOps WG - move to the backlog for now.  This is slated to be reworked.

**Comment by jamesrgregg** [comment]
Work around was to change the build node to use more compute - 4c-16g

**Comment by jamesrgregg** [comment]
TSC update today from @cloudxxx8 did not report any ARM build failures within blackbox tests.
Closing issue with conclusion that change to the build node helped resolve issue.
