### ISSUE TITLE
New build automation for go-mod-bootstrap

### ISSUE THREAD

**Issue by jamesrgregg** [edgexfoundry/ci-management#523]
Repo will soon be moved out of holding to main Org.
We will need new Pipeline for the go-mod-bootstrap repo.

[US5832](https://rally1.rallydev.com/#/detail/userstory/354180156408?fdp=true)

**Comment by michaelestrin** [comment]
https://github.com/edgexfoundry/go-mod-bootstrap is available for pipeline creation.  @jamesrgregg

**Comment by jamesrgregg** [comment]
@michaelestrin we'll pull that user story into the next sprint or ASAP if we get bandwidth sooner
