### ISSUE TITLE
New build automation for go-mod-configuration

### ISSUE THREAD

**Issue by jamesrgregg** [edgexfoundry/ci-management#540]
BLOCKED - still in HOLDING
[US5932](https://rally1.rallydev.com/#/detail/userstory/360387546896?fdp=true)

**Comment by jamesrgregg** [comment]
[US5932](https://rally1.rallydev.com/#/detail/userstory/360387546896?fdp=true)

**Comment by ernestojeda** [comment]
Lenny finished the automation per this PR: https://github.com/edgexfoundry/go-mod-configuration/pull/4
