### ISSUE TITLE
Set Go Version to 1.13x in Verify Jobs

### ISSUE THREAD

**Issue by tsconn23** [edgexfoundry/ci-management#567]
It appears the following job is configured to use Go 1.11.x.

https://jenkins.edgexfoundry.org/job/edgex-go-master-verify-go/configure

If you scroll down to the Build section, you'll see the following
<img width="1200" alt="Screen Shot 2020-02-06 at 9 05 11 AM" src="https://user-images.githubusercontent.com/1342980/73949565-3185e280-48c0-11ea-8154-520b44457429.png" />

The request is to bump the referenced version of Go to 1.13.x in this verification pipeline and to check all other Go-based project pipelines for same.

This is in preparation for moving the project to Go 1.13 per agreed upon Geneva deliverable
https://wiki.edgexfoundry.org/display/FA/Geneva+Release

**Comment by ernestojeda** [comment]
@tsconn23 Should we also bump the Go version in each of the Dockerfile's in the cmd folder. For example:

https://github.com/edgexfoundry/edgex-go/blob/master/cmd/config-seed/Dockerfile#L19
https://github.com/edgexfoundry/edgex-go/blob/master/cmd/core-command/Dockerfile#L9
https://github.com/edgexfoundry/edgex-go/blob/master/cmd/core-metadata/Dockerfile#L9
...etc

**Comment by tsconn23** [comment]
@ernestojeda Yes, that can be done separately though.

**Comment by tsconn23** [comment]
Dockerfile mods for core/support/SMA services
https://github.com/edgexfoundry/edgex-go/issues/2341

**Comment by tsconn23** [comment]
@ernestojeda Go version has been rev'ed in Dockerfiles. Are there follow-up action items from your end?

**Comment by jamesrgregg** [comment]
Checked the running pipeline and each arch build shows the correct go version 1.13
00:03:53.102  go version go1.13 linux/amd64
00:04:14.453  go version go1.13 linux/arm64

Running Pipeline is for most recent PR-2040
https://jenkins.edgexfoundry.org/view/EdgeX%20Foundry%20Project/job/edgexfoundry/job/edgex-go/view/change-requests/job/PR-2040/35/console

**Comment by lranjbar** [comment]
Closed as fixed.
