### ISSUE TITLE
The V1 APIs on edgex-go also need to publish to swaggerhub

### ISSUE THREAD

**Issue by cherrycl** [edgexfoundry/ci-management#579]
I found the edgex-go [jenkins build](https://jenkins.edgexfoundry.org/view/EdgeX%20Foundry%20Project/job/edgexfoundry/job/edgex-go/job/master/4/consoleFull) only execute publishing v2 APIs to SwaggerHub.
The v1 APIs also need to publish to SwaggerHub by jenkins job.

- V1 APIs put on [edgex-go/api/openapi/v1](https://github.com/edgexfoundry/edgex-go/tree/master/api/openapi/v1)
- The [shell script](https://github.com/edgexfoundry/ci-management/blob/master/shell/edgex-publish-swagger.sh) didn't see any v1 API input.

**Comment by cloudxxx8** [comment]
@ernestojeda could you please also add V1 API export for the API documentation?  thank you

**Comment by jamesrgregg** [comment]
[US6239](https://rally1.rallydev.com/#/detail/userstory/372790834996?fdp=true): EdgeX DevOps: Add V1 APIs to edgex-publish-swagger.sh

**Comment by cherrycl** [comment]
Currently, please set API_VERSION to 1.1.1 when publishing the v1 API to SwaggerHub. Thank you.

**Comment by cherrycl** [comment]
@jamesrgregg Would you please reassign this issue to me? I found both 2 variables, API Version and isPrivate, should be removed when publishing API to SwaggerHub. I can consult @ernestojeda for adding the another publish on edgex-publish-swagger.sh.

**Comment by ernestojeda** [comment]
@cherrycl Let me know if you need any help on this.
