### ISSUE TITLE
Need to change the schedule for blackbox-testing

### ISSUE THREAD

**Issue by cherrycl** [edgexfoundry/ci-management#586]
As @bnevis-i mentioned on [slack](https://edgexfoundry.slack.com/archives/CE44Z88NL/p1582991849008300). The schedule of blackbox-testing needs to change to 8 pm (0400 UTC).

**Comment by bnevis-i** [comment]
@cherrycl   This is great at it will close the gap from 19 hours between build and test to only 11 hours.  Where does the coresponding change to build need to be made so that we can reduce the gap to only 2 hours?
